# Generated by Django 6.0.3 on 2026-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(default='2026-03-28'),
            preserve_default=False,
        ),
    ]
